* *************************JAVA BASICS****************************************************

* Java is a class based, object oriented programming language and is designed to have as few implementation dependencies as possible

* Java does not provide low level programming functionalities like pointers

* Java is used in all kind of applications like *Mobile Applications* (Android is Java based), *desktop applications, *web applications, *client server applications, *enterprise applications and many more.

#programs written in Java typically run faster than corresponding Python programs and slower than C++. 

#Java Virtual Machine(JVM): Compiler converts source code to bytecode and then the JVM executes the bytecode generated by the compiler. 
Phases of program: Write Code, Compile, Run
* Writing a program
* compilation is done by JAVAC compiler which is a primary Java compiler included in the Java development kit (JDK)
*  JAVAC compiler takes Java program as input and generates bytecode as output.
# JVM executes the bytecode generated by the compiler.

# Java is known as a platform independent language::::::::because every Operating System has different JVM but the output they produce after the execution of bytecode is the same across all the operating systems.

#Java Development Kit(JDK):
* it is a complete java development kit that includes everything including compiler, Java Runtime Environment (JRE), java debuggers, java docs etc. 
* For the program to execute in java, we need to install JDK in our computer in order to create, compile and run the java program.

#Java Runtime Environment (JRE):
* JDK includes JRE.
* JRE includes a browser, JVM, applet supports and plugins. For running the java program, a computer needs JRE.
* JRE need for java program to run, however we cannot compile it

#Primary/Main Features of Java********************

1. Platform Independent: 

2. Object-Oriented Programming Language:

Four main concepts of Object Oriented programming are:

*Abstraction
*Encapsulation
*Inheritance
*Polymorphism

3. Simple:  
as it does not have complex features like pointers, operator overloading, Multiple inheritance, Explicit memory allocation. 

4. Robust:
:  means reliable.
: Java can find minute errors that is not possible by others
: The main features of java that make it robust are garbage collection, Exception Handling and memory allocation.

5. Secure: 

6. Distributed:
: can create distributed applications
:  java programs can be easily distributed on one or more systems that are connected to each other through an internet connection.

7. Multithreading:
allows concurrent execution of two or more parts of a program for maximum utilization of CPU.

8. Portable:  
Platform Independent nature of java makes it portable on every platform.